services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  migrate:
    image: migrate/migrate
    command: [ "-path", "/migrations", "-database",  "mysql://root:root@tcp(mysql:3306)/orders", "up" ]
    volumes:
      - ./internal/infra/database/sql/migrations:/migrations
    depends_on:
      mysql:
        condition: service_healthy

  queue:
    build:
      context: ./internal/infra/rabbitmq/
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"
      - "50051:50051"
      - "8080:8080"
    depends_on:
      queue:
        condition: service_healthy
      mysql:
        condition: service_healthy
    env_file:
      - ./cmd/ordersystem/.env

volumes:
  mysql_data:
